
/* Simple adventure/ combat script for Mechanical Elf Saga */
const gameData={hero:{hp:100,maxHp:100,attack:12,defense:3,potions:2},enemies:[{name:"Bone Skeleton",hp:30,maxHp:30,attack:6,defense:1},{name:"Street Cat",hp:45,maxHp:45,attack:8,defense:2},{name:"Anexo Goblin",hp:60,maxHp:60,attack:10,defense:3}],boss:{name:"Mechanical Elf",hp:120,maxHp:120,attack:18,defense:5},muted:false};
const narration=document.getElementById('narration'),choices=document.getElementById('choices'),startBtn=document.getElementById('startBtn'),startScreen=document.getElementById('startScreen'),gameScreen=document.getElementById('gameScreen'),heroHP=document.getElementById('heroHP'),heroHPtext=document.getElementById('heroHPtext'),enemyHP=document.getElementById('enemyHP'),enemyHPtext=document.getElementById('enemyHPtext'),enemyName=document.getElementById('enemyName'),bgMusic=document.getElementById('bgMusic'),combatMusic=document.getElementById('combatMusic'),soundClick=document.getElementById('soundClick'),soundAttack=document.getElementById('soundAttack'),soundDefend=document.getElementById('soundDefend'),soundHeal=document.getElementById('soundHeal'),soundCrit=document.getElementById('soundCrit'),soundEnemyAttack=document.getElementById('soundEnemyAttack'),muteBtn=document.getElementById('muteBtn');
let currentScene=0,inCombat=false,currentEnemy=null,isDefending=false;
const scenes=[{text:"You awaken in neon shadows beneath Oaxaca...",choices:[{t:"Step forward",n:1},{t:"Look around",n:2}]},{text:"A skeleton blocks your path!",choices:[{t:"Fight",n:"fight"}]}];
function play(audio){if(!gameData.muted){audio.currentTime=0;audio.play()}}
function showScene(){inCombat=false;currentEnemy=null;updateBars();const s=scenes[currentScene];narration.textContent=s.text;choices.innerHTML='';s.choices.forEach(c=>{const b=document.createElement('button');b.textContent=c.t;b.className='choice-btn';b.onclick=()=>{play(soundClick);if(typeof c.n==='number'){currentScene=c.n;showScene()}else if(c.n==='fight'){startFight(gameData.enemies[0])}};choices.appendChild(b)})}
function updateBars(){heroHPtext.textContent=`${gameData.hero.hp}/${gameData.hero.maxHp}`;heroHP.style.width=`${gameData.hero.hp/gameData.hero.maxHp*100}%`;if(currentEnemy){enemyName.textContent=currentEnemy.name;enemyHPtext.textContent=`${currentEnemy.hp}/${currentEnemy.maxHp}`;enemyHP.style.width=`${currentEnemy.hp/currentEnemy.maxHp*100}%`}else{enemyName.textContent='';enemyHPtext.textContent='';enemyHP.style.width='0'}}
function startFight(enemy){inCombat=true;currentEnemy={...enemy};bgMusic.pause();play(combatMusic);renderFight()}
function renderFight(){updateBars();narration.textContent=`${currentEnemy.name} prepares to attack!`;choices.innerHTML='';['Attack','Defend','Heal'].forEach(act=>{const b=document.createElement('button');b.className='choice-btn';b.textContent=act;b.onclick=()=>playerAction(act);choices.appendChild(b)})}
function playerAction(act){if(act==='Attack'){play(soundAttack);let dmg=gameData.hero.attack-(currentEnemy.defense||0);if(Math.random()<.2){dmg*=2;play(soundCrit)}currentEnemy.hp=Math.max(0,currentEnemy.hp-dmg);if(currentEnemy.hp<=0){winFight();return}}else if(act==='Defend'){isDefending=true;play(soundDefend)}else if(act==='Heal'){if(gameData.hero.potions>0){gameData.hero.hp=Math.min(gameData.hero.maxHp,gameData.hero.hp+20);gameData.hero.potions--;play(soundHeal)}}
enemyTurn()}
function enemyTurn(){let dmg=currentEnemy.attack-(gameData.hero.defense||0);if(isDefending)dmg=Math.floor(dmg/2);gameData.hero.hp=Math.max(0,gameData.hero.hp-dmg);play(soundEnemyAttack);isDefending=false;if(gameData.hero.hp<=0){gameOver();return}renderFight()}
function winFight(){combatMusic.pause();play(bgMusic); narration.textContent=`You defeated ${currentEnemy.name}!`;choices.innerHTML='<button class="choice-btn">Continue</button>';choices.firstChild.onclick=()=>{currentScene++;showScene()}}
function gameOver(){combatMusic.pause();narration.textContent='You have been defeated...';choices.innerHTML='<button class="choice-btn">Restart</button>';choices.firstChild.onclick=restart}
function restart(){location.reload()}
startBtn.onclick=()=>{startScreen.classList.remove('active');gameScreen.classList.add('active');play(bgMusic);showScene()}
muteBtn.onclick=()=>{gameData.muted=!gameData.muted;if(gameData.muted){bgMusic.pause();combatMusic.pause();muteBtn.textContent='🔇'}else{if(inCombat)play(combatMusic);else play(bgMusic);muteBtn.textContent='🔊'}}
